[//]: # (https://stackoverflow.com/questions/4823468/comments-in-markdown)
[//]: # remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
[//]: # remote_theme: pages-themes/cayman@v0.2.0
[//]: # remote_theme: pages-themes/dinky@v0.2.0
[//]: # remote_theme: pages-themes/modernist@v0.2.0
title: [Патофизиология сердечно-сосудистой системы]
[//]: # title: [<span style="font-size:1.5em;">Патофизиология сердца и сосудов</span>]
